[[constraint]]
  branch = "master"
  name = "code.cloudfoundry.org/lager"

[[constraint]]
branch = "master"
  name = "github.com/hashicorp/vault"

[[constraint]]
  branch = "master"
  name = "github.com/pivotal-cf/brokerapi"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"
